### ISSUE TITLE
Inconsistent unit tests in local install

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pydm#1012]
**Describe the bug**

Several of the pydm unit tests report failures when run on my conda environments on LCLS photon-side servers depending on how I run the tests.

I suspect these are test suite bugs rather than core pydm bugs.

***First Issue***
If I run the tests normally after activating my conda env, the following tests fail with timeout errors. Note that sometimes more or fewer tests fail here, usually 8-10 of the tests fail:
```
FAILED pydm/tests/widgets/test_lineedit.py::test_set_display[123-True-int-0-3-1-s-True] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_set_display[123-True-int-0-3-1-s-False] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_set_display[value8-str-True-0-3-2-degree-True] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_in_event[False-1-False] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_in_event[False-3-False] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_in_event[False-0-True] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_out_event[123] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_out_event[123.456] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
FAILED pydm/tests/widgets/test_lineedit.py::test_focus_out_event[] - pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds
```

If, instead, I run with `export QT_QPA_PLATFORM=offscreen`, as we always do when running in the github actions, these tests all pass no problem, even locally. I think this must be a timing bug that depends on the rendering timing that is avoided when running in offscreen (no windows) mode.

***Second Issue***
If I run the unit tests with my group's pydm stylesheet active, the following tests additionally fail:
```
FAILED pydm/tests/utilities/test_stylesheet.py::test_stylesheet_get_style_data - assert 2 == 1
FAILED pydm/tests/widgets/test_drawing.py::test_pydmdrawing_paintEvent[True] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[1-True-True] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[1-True-False] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[2-True-True] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[2-True-False] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[3-True-True] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[3-True-False] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[4-True-True] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_label.py::test_label_alarms[4-True-False] - AssertionError: assert '#000000' != '#000000'
FAILED pydm/tests/widgets/test_related_display_button.py::test_no_pydm_app_stylesheet - TypeError: 'in <string>' requires string as left operand, not NoneType
```
To set this test up I used:
```
$ export QT_QPA_PLATFORM=offscreen
$ export PYDM_STYLESHEET="${EPICS_ROOT}/screens/pydm/vacuumscreens/styleSheet/masterStyleSheet.qss"
$ export PYDM_STYLESHEET_INCLUDE_DEFAULT=1
```
This stylesheet is available online at https://github.com/pcdshub/vacuumscreens/blob/master/styleSheet/masterStyleSheet.qss and largely serves to define behavior in some custom vacuum widgets.

**Expected behavior**

It'd be nice if these tests were more consistent so that we could verify conda environment installs with confidence. I now know that I have to unset my group's stylesheet and run in offscreen mode but that's not how the screens are typically run for me in prod.

**Steps to Reproduce**

1. Set environment variables appropriately
2. `pytest` (ignoring the psp test)

**My Platform**

red hat 7
pydm 1.19.1
python 3.9.15
numpy 1.23.5
pyqt 5.12.3
qt 5.12.9
pyqtgraph 0.12.4

**Additional context**

I run all of my groups unit tests + a bunch of unit tests from important packages, including pydm, before deploying a conda environment. I've noticed these issues while running these tests.

**Comment by jbellister-slac** [comment]
Thanks for reporting these. I was actually taking a quick look at the line edit tests recently, I was testing a rather brute force solution of just repeatedly attempting to get focus where it doesn't actually affect what the test is checking for like here df84dcf185f68a1a5e48009ceebad8295ed928bd, I'll take another look at all of those.

The stylesheet issue I was not aware of, I will take a look at that as well.
