### ISSUE TITLE
ENH: Rich Text editor for PyDMLabels

### ISSUE THREAD

**Issue by kabanaty** [slaclab/pydm#1013]
**What's the problem this feature will solve?**
PyDMLabels do not support rich text like QLabels do.

**Describe the solution you'd like**
Allow rich text to be used on PyDMLabels.

**Additional context**
I'd like to have a label that is displayed via Visibility Rule.  I can have rich text via QLabel, or Rule functionality via PyDMLabel, but not both.

**Comment by nstelter-slac** [comment]
Hi,

Looks like adding rich text to PyDMLabel is just setting the classes textFormat to rich text(https://github.com/slaclab/pydm/pull/1020). This works when setting the "text" value of the label.

But this doesn't apply the rich text when the label is displaying values from a channel. To add this, we would need to extract the rich-text formatting from the user entered channel. For example, extract and apply the <b>'s from an input: "<b>ca://MTEST:Float<b>".

Is seeing rich text with channel data what's wanted?

**Comment by kabanaty** [comment]
I’m not interested in applying rich text to channel readbacks, nor do I think it’s a good idea. I would like to be able to use the rules functionality of the PyDMLabel to hide/show a PyDMLabel with rich text
