### ISSUE TITLE
Request to fix a bug that stops develops from changing icons on related displays in designer.

### ISSUE THREAD

**Issue by phys-cgarnier** [slaclab/pydm#1031]
**Describe the bug**
The PyDMShellCommand support for choosing a new icon does work.
In python you can manually set the icon for a PyDMShellCommand to other themes. (i.e I can make a PyDMShellCommand look like a related display by changing the icon to a file instead of a gear.)
However, in Designer changing the icon does not appear to work.

**Steps to Reproduce**
Check that it is possible to check the PyDMShellCommand icon from a gear to a file in python.
Check that the same thing is not recreatable in Designer.

**My Platform**
I am working on mcclogin and dev3.

**Comment by Ryan-McClanahan** [comment]
Easy second from me.  I thought I made this issue before, but it does not look like it.  Just talked about it in a slack channel.

Has anyone had trouble using icons in designer?  I can implement them fine when I make a hybrid or pure python display.  But in designer they do not seem to work. I copied a script from the pyqt documentation and ran it with pydm.  So it seems like we have access to the icons, just not in designer.  The process I followed to try to change the icons in designer is detailed here https://www.pythonguis.com/faq/are-there-any-built-in-qicons/#:~:text=Qt%20ships%20with%20a%20small,standardIcon(name)%20.

**Comment by nstelter-slac** [comment]
https://forum.qt.io/topic/61476/using-qtstyle-standard-icons-in-qt-designer:

_"One is for resource file and directly above it is a text field for a standard icon from theme.
The generated code for this uses [QIcon::fromTheme()](http://doc.qt.io/qt-5/qicon.html#fromTheme) and thus falls under some restrictions: the available names list is listed [here](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names)."_

So seems designer limits use of the QStyle icons (ex: QStyle::SP_ArrowBack).

But in designer on Linux you should be able to set any of the "Icon Theme Specification" icons listed here: http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names. 
(can "Set Icon From Theme" and then paste any of the icon-names from the link)

**Comment by nstelter-slac** [comment]
setting icons from the "Icon Theme Specification" works on my linux desktop but doesn't seem to work on my linux laptop (thinking maybe some desktop environments (xfce?) do not provide the icons by default?).

but realized since setting the qt-provided icons work in python, 
we can allow these to be set in designer by exposing a custom property that sets the icon in python inside the property's setter.
this should provide icons on all machines, since they ship with qt.

**Comment by Ryan-McClanahan** [comment]
Hey!

This is great!  When do you think we'll be able to test this on our fastx environment?

Kind Regards,

Ryan
________________________________

**Comment by jbellister-slac** [comment]
Hi Ryan, this should be available for use in our environment on this Wednesday
