### ISSUE TITLE
PyDMEventPlot is missing documentation

### ISSUE THREAD

**Issue by ivan-usov** [slaclab/pydm#1041]
While looking at the pydm source code, I realized that not all plot widgets are present in documentation. For example, there is one missing: PyDMEventPlot (https://github.com/slaclab/pydm/blob/master/pydm/widgets/eventplot.py).

It would be very useful to have a good overview of pydm possibilities directly via documentation, especially for pydm newbies, as it turns out to be something I was looking for, but had to make a workaround with another plot type. 

There seems to be a generic issue for widgets documentation, though a bit stale: https://github.com/slaclab/pydm/issues/280
However, it doesn't contain PyDMEventPlot on the list neither.

**Comment by nstelter-slac** [comment]
Added missing doc page for PyDMEventPlot here: https://github.com/slaclab/pydm/pull/1043, we can merge this now.

Agree with https://github.com/slaclab/pydm/issues/280 that it would be best to add description paragraphs to the pages for all widgets eventually, like we have for [PyDMTabWidget](http://slaclab.github.io/pydm/widgets/tab_widget.html#pydmtabwidget).
