### ISSUE TITLE
Toggle Navigator Visible / Invisible

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#105]
The navigator definitely needs to be something that can be toggled.
@mattgibbs

**Comment by mattgibbs** [comment]
I think it should be implemented like this:
- [ ] Make forward/back/home/go QActions (with hotkeys).
- [ ] Make the navigation bar a QToolbar that uses those QActions.  (Need to modify pydm/pydm.ui and run pyuic4 on it for this part)
- [ ] Add a (checkable) menu action in the view menu to toggle the navbar on/off.  The action can just call QMainWindow.setToolbar and QMainWindow.removeToolbar.  Navbar is shown by default.
- [ ] Also add a 'history' menu onto the menu bar with the same QActions.  Extra credit: Add items into the history menu for the 5 most recent displays on the navigation stack.

**Comment by hhslepicka** [comment]
Attn. @ZLLentz ... @mattgibbs will work on this issue soon!
