### ISSUE TITLE
testing-ioc.py: image PV data type and no hint to EPICS_CA_MAX_ARRAY_BYTES

### ISSUE THREAD

**Issue by mennodoor** [slaclab/pydm#110]
Hi all!

Is there a good reason for using character type in the Image PV of testing-ioc.py? I normally use int for images or waveforms and it works fine.

Also for beginners which may have not set environmental variables yet, it would be nice to have this snippet also in the testing-ioc:
```
import os
os.environ['EPICS_CA_MAX_ARRAY_BYTES'] = IMAGE_SIZE**2 + 1
```
including some comment, why you need this.

Greetings
menno

**Comment by mennodoor** [comment]
ah... it is a pretty good reason if you do this to reduce the amount of bytes to transfer... i have to take a look on #109 again...

**Comment by hhslepicka** [comment]
@mennodoor that is exactly the reason!
Let me know what you think of this idea:

PyDMLabel and PyDMLineEdit would offer PyQTProperties to determine the way to output the value with the following options:

- Default: What you see is what is available at the PV get...
- String: We will do our best to convert it to a String...
- Decimal: Only useful for int and float data... use the precision to format
- Exponential: Almost the same as Decimal
- Hex: Hexadecimal representation of the number
- Binary: Binary representation of the number...

@mattgibbs and I noticed that there is no much use for the formatting of data outside of those 2 widgets... let me know if you agree! 👍

**Comment by mennodoor** [comment]
I do agree. You can actually just use the char_value already given by pyepics to connect to the value signal and connect the value to the waveform signal. In this case how ever, it will stop working after the unification of waveform and value. 
Doing the formatting stuff inside the widgets will be definitely a cleaner solution...

**Comment by hhslepicka** [comment]
Closing as this is a configuration that ends up being site-specific. If we poke with it we can end up generating weird side effects.
