### ISSUE TITLE
Fix PYQTDESIGNERPATH mechanism for pydm pip installations?

### ISSUE THREAD

**Issue by peroame** [slaclab/pydm#1105]
When installing pydm through pip, the PYQTDESIGNERPATH designer mechanism designer doesn't seem to work, ie the pydm widgets are not visible. I believe this is because the designer needs to read pydm_designer_plugin.py but the pip installation starts from one level below the top pydm directory that contains that file. If this is true, I believe it would be worth fixing pip pydm, if not, please let me know what I'm missing.

Thank you!
Amedeo

**Comment by nstelter-slac** [comment]
ive put up a patch that should fix this issue (still needs review + merge)

but i'll list some info that could be useful:
- for designer to be able to load pydm widgets, you must have older version from installing PyQt version 5.12.3 or lower (in your conda install, can pin this version with 'pyqt=5.12.3'). More info here: https://slaclab.github.io/pydm/installation.html
- running `designer` cmd from terminal will launch it directly, and if pydm widgets load properly you should see "Loading PyDM Widgets" output in terminal
- _(after new patch merges)_ if you install pydm with pip using a local copy of the repo ('pip install -e .' from inside the pydm project root), you will need to point `PYQTDESIGNERPATH` to `<pydm_root_dir>/pydm` (where pydm_designer_plugin.py lives)
- _(after new patch merges)_ if you install pydm with pip from PyPI, you need to point  `PYQTDESIGNERPATH` to pip's pydm install location (can find by running `pip show pydm` and appending `/pydm` to the `Location` field), where you can also confirm the pydm_designer_plugin.py file exists.
