### ISSUE TITLE
Deprecate Qt4

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#114]
Opening this issue for the discussion of abandoning Qt4 in favor of more modern and well maintained Qt5.
Other libraries such as matplotlib already moved to Qt5 and the performance with PyDM is better when using it.
Qt5 will also allow us to use more advanced resources such as Custom ENUMS as properties on the widgets and more.

Please weight in @mattgibbs @mennodoor @laispc @gabrielfedel and feel free to tag others...

**Comment by gabrielfedel** [comment]
Me and @laispc already use just qt5, so, for us, it's ok deprecate qt4!

**Comment by hhslepicka** [comment]
After this period for discussion and new issues that were faced with multiple inheritance and Qt4 Designer not being able to correctly interpret that and show the qtproperties properly it was decided that PyDM will no longer offer support for QT4 & PyQt4.

Thank you Qt4 for your service, now it is time for you to rest. 💀
