### ISSUE TITLE
PSP EPICS plugin only updates read/write access when PV value changes.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#116]
If the read/write access state of a PV changes after the PV has connected, psp_plugin won't catch access state changes unless the PV value changes or connection state changes.  I've submitted a PR to add support for this into pyca: https://github.com/slaclab/pyca/pull/1

Until that PR is merged, we'll just have to live with this.

**Comment by hhslepicka** [comment]
@mattgibbs is this now solved since you reworked the PSP plugin?

**Comment by mattgibbs** [comment]
Oh yeah!  This is now solved.
