### ISSUE TITLE
Hide menu bar

### ISSUE THREAD

**Issue by joaopmrod** [slaclab/pydm#149]
Option to hide the menu bar (File, View, History).

**Comment by mattgibbs** [comment]
Hi Joao, is this because you see the menu bar when you make PyDM full-screen?  Or do you want the ability to hide the menu bar even when displaying a normal-sized window?

**Comment by joaopmrod** [comment]
Hi, Mike wants to hide the menu bar even when in normal-sized window mode.

Thank you
Matt Gibbs <notifications@github.com> escreveu em qua, 25 de out de 2017 às
13:19 :
