### ISSUE TITLE
Clicking a related display button without the displayFilename property set crashes the app.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#15]
Button should be disabled until displayFilename is set.

**Comment by hhslepicka** [comment]
@mattgibbs can you provide a test case for this bug?

**Comment by mattgibbs** [comment]
The related display button wasn't doing any error handling when opening files, so if you had a blank string for the displayFilename property, it would crash (actually, ANY invalid filename would crash).  Thanks to your fixes involving opening files, is was pretty easy to handle the error now.  Also made it so for blank displayFilenames, the button gets disabled, so you can't even *try* to click it.

**Comment by hhslepicka** [comment]
Awesome! I was working on this item but I am glad that the previous worked made it easier! 👍
