### ISSUE TITLE
PyDM sometimes hangs on exit when connected to hundreds of PVs.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#18]
If you launch a display that connects to large numbers of PVs, then try to close the display, sometimes PyDM will hang, and need to be forcefully terminated.

**Comment by mattgibbs** [comment]
I should note - this is when using psp_plugin as the EPICS data plugin.  Unclear if this problem exists for PyEpics.

**Comment by hhslepicka** [comment]
@mattgibbs, how large is large in this case? 1000 PVs?

**Comment by mattgibbs** [comment]
I know it happens almost every time with 500 PVs, and almost never with something like 10 PVs.

**Comment by hhslepicka** [comment]
Tested with 1000PVs using the `code_only.py` example and it no longer hangs at exit.
Closing as this was probably fixed in one of the many refactors that we did recently.
