### ISSUE TITLE
Can't remove icons from shell commands and related display buttons in Designer.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#225]
It appears that there is no easy way to get rid of the icons on PyDMShellCommand and PyDMRelatedDisplay buttons without writing code to do it.  The buttons have an 'icon' property in Designer that comes from QAbstractButton, but that doesn't provide any way to clear out an existing icon, just change it to a new one.

A workaround is to make the icon size 0x0, but this is a pretty unintuitive way to get rid of it.

**Comment by hhslepicka** [comment]
Oops! My bad for not catching this before!
Can’t you remove or clear the bitmap from the selection window?

**Comment by mattgibbs** [comment]
No.  Really, I think that it is mostly Designer’s fault that you can’t clear it out easily.  Oh well, I guess we need some kind of boolean property for it.

—Matt

**Comment by hhslepicka** [comment]
That is a good idea! ;) A simple showIcon property would do it! ;)
