### ISSUE TITLE
enum_combo doesn's change PV value 

### ISSUE THREAD

**Issue by gabrielfedel** [slaclab/pydm#27]
When I use enum_combo, for a ENUM, if a change combo it doesn't change PV.
I tried a fix on add_listener from pyepics_plugin :

```
 try:                                                                      
   channel.value_signal[str].connect(self.put_value, Qt.QueuedConnection)  
 except:                                                                   
   pass                                                                    
 try:                                                                      
   channel.value_signal[int].connect(self.put_value, Qt.QueuedConnection)  
 except:                                                                   
   pass                                                                    
 try:                                                                      
   channel.value_signal[float].connect(self.put_value, Qt.QueuedConnection)
 except:                                                                   
   pass                                                                    

```

This fix the the problem, but the combo always go back to first item (it set correctly the PV, but doesn't show value correct).

**Comment by mattgibbs** [comment]
Hmmm.  I haven’t experienced this myself.  I’m doing this and it works as expected:
$ python testing-ioc.py &
$ python pydm.py examples/oscilloscope/scope.ui
There is an enum combo on the scope panel to change between ‘STOP’ and ‘RUN’, change it.

Can you tell me if that is working for you?  Trying to isolate if it is an issue with a particular PV or all of PyDM…
—Matt

**Comment by gabrielfedel** [comment]
Hello @mattgibbs , I tried this example but didn't work : when window open, emits some messages off "Identical process variable names on multiple servers", and combo items are pink.
I tried to change but nothing happens

**Comment by anacso17** [comment]
I used the changes on add_listener from pyepics_plugin and it worked with me too. 

To change the value of the combo box I commented the line 119 from enum_combo_box.py. 
`  @pyqtSlot(int)
  def internal_combo_box_activated_int(self, index):
    if self._value != index:
     # self._value = index
      self.valueChanged.emit(index)
self.activated[int].emit(index)`
The value (index) of the combo_box can only be changed by receiveValue, and not in valueChanged signal.
