### ISSUE TITLE
Problem when using the same PV on window and code (with pyepics)

### ISSUE THREAD

**Issue by gabrielfedel** [slaclab/pydm#28]
I made a program using pydm, and I put a PV on window, and create the same PV (with pyepics) on the code. When I change pyepics PV, pyepics_plugin (from pydm) receive a callback on send_new_value, but the value is None and it's broke pydm.

I work around this adding a verification if value is None on send_new_value, but I'm not sure if the problem origin is pyepics or pydm.

**Comment by hhslepicka** [comment]
Can you provide some basic code to reproduce this issue?

**Comment by gabrielfedel** [comment]
Sure!:

https://gist.github.com/gabrielfedel/043603d5ff6b2d33aecb80e5fcd1121e

**Comment by gabrielfedel** [comment]
Now I see the problem happens when change value

**Comment by mattgibbs** [comment]
Thank you for finding the bug, Gabriel!
