### ISSUE TITLE
Memory Issue with PyDMImageView

### ISSUE THREAD

**Issue by fernandohds564** [slaclab/pydm#288]
There is a problem with the widget `PyDMImageView` when it is connected to PVs of type `'int'` provided by a pcaspy Server.  As soon as a `PyDMApplication` with this widget starts execution, the memory allocated by the process increases, using all the memory of my computer (32Gb).

This issue can be reproduced by changing the type of the PV `ca://MTEST:Image` of `pydm-testing-ioc.py` to `'int'` and changing the value of variable `IMAGE_SIZE` of the same module to `200.`

I have noticed that this is the line which is causing problem:
https://github.com/slaclab/pydm/blob/0213d9c86734a8b5ab553675001a3d83ac00a5df/pydm/widgets/image.py#L224

I think this issue holds for any PV of type `int32`, but I have not tested it with real IOCs.

**Comment by hhslepicka** [comment]
Hi @fernandohds564,
Thank you for reporting this issue.
I am almost sure that the offending code is the setColorbar and not np.iinfo since the second only returns the boundaries of the data type.
I will investigate how to solve this problem and come back to this issue with a possible solution.

**Comment by fernandohds564** [comment]
Yes @hhslepicka, you are correct.
I copied the wrong line, the one which is causing problem is the creation of the `lookupTable`:

https://github.com/slaclab/pydm/blob/0213d9c86734a8b5ab553675001a3d83ac00a5df/pydm/widgets/image.py#L194

I think @anacso17 is working on a PR to solve this issue.

**Comment by hhslepicka** [comment]
@fernandohds564 that would be awesome! 
I will wait for @anacso17.

**Comment by hhslepicka** [comment]
@anacso17 will do! Thank you!

**Comment by hhslepicka** [comment]
Solved with #289. Thank you, @anacso17
