### ISSUE TITLE
BaseWidget does not allow visible QFrame

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pydm#313]
`PyDM` does not currently allow any of its widgets to have a frame. The alarm handling on the base widget sets the frame to `"transparent"` if there is no alarm.

https://github.com/slaclab/pydm/blob/67d777913ce86c8a80374034b32d2995259203ea/pydm/widgets/base.py#L158

It seems like the base widget should preserve the `"border"` stylesheet that is set originally and restore this when there is no alarm. This would allow Stylesheets that have PyDM widgets with borders but still implement the standard alarm handling.

**Comment by hhslepicka** [comment]
This will be fixed with #361 .
