### ISSUE TITLE
PyDMEnumComboBox is actually not a QComboBox

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pydm#314]
Ran into some issues with this and found this rather unintuitive. The `PyDMEnumComboBox` is actually a `QFrame` with a layout inside it that contains a `QComboBox`.

https://github.com/slaclab/pydm/blob/67d777913ce86c8a80374034b32d2995259203ea/pydm/widgets/enum_combo_box.py#L37-L39

Curious what the reason for this is? It makes it so things you would expect to work form the `QComboBox` API to not work on `PyDMEnumComboBox` which was unexpected based on the name. The layout also causes some sizing issues because of the margins of the widget.

**Comment by mattgibbs** [comment]
I think this is a vestige of how we used to do an alarm border around this widget.  Now that we have PyDMFrame, we should consider just making this a plain-old subclass of QComboBox.

--Matt
