### ISSUE TITLE
Local Plugin needs urgent review

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#329]
We need to make sure that we have a local plugin or remove it from the package.
I have absolutely no idea how the code available works.

**Comment by ZLLentz** [comment]
I wrote this one a year or more ago. The motivation behind it is mostly replaced with projects like `typhon`. I don't remember how it works, but the goal was to display an object's properties and method results inside of `pydm` widgets so we could define object classes that include logic and use them in both our `pydm` screen and in other libraries. I doubt anyone has used it, and I didn't use it 6 months later when I needed to integrate `ophyd` objects into a screen.

**Comment by nstelter-slac** [comment]
Outdated issue
