### ISSUE TITLE
Types other than str for items on the ComboBox

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#331]
Just bringing the discussion at #322 to a clean issue so we can discuss and decide how to attack this issue if we decide to go forward.

What if someone wants to point to an array of integer or floats or booleans.... shouldn't we allow and just cast down there... if the cast fails we barf?

**Comment by mattgibbs** [comment]
My view is that PyDMEnumComboBox was written with *enums* in mind, which are basically an int->string map.  I am not sure we want to wade into making it very general purpose.  QComboBox is pretty easy to use on its own, and it should probably be used directly by people that want to do something more custom.
