### ISSUE TITLE
Related Display Buttons should forward all macro variables to the display they open.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#342]
It seems that sometimes, macros aren't getting forwarded properly.  For example, on a panel where the '${MOTOR}' macro variable is defined, if you add a related display button, you need to set the button up with a macro like this: {"MOTOR":"${MOTOR}"} to manually forward the macro to the new display.  That is supposed to be done by default.

**Comment by hhslepicka** [comment]
@mattgibbs is this fixed?

**Comment by klauer** [comment]
This is not yet fixed - I just ran into it. Mine was from an embedded display with a related display button. I'll see if I can quickly get to the bottom of it.
