### ISSUE TITLE
Get rid of the 'whats this' info in Designer plugins.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#373]
Right now we populate the 'whats this' field with the docstring for the widget, but this is nearly useless in practice (you can't read more than a line of it in a tooltip in Designer, the only place it shows up), and because it is repeated for every instance of the widget, it significantly bloats the .ui files.

**Comment by hhslepicka** [comment]
Big 👍 to that! We can add it on the widget rules PR since there we poke with the designer plugins.
