### ISSUE TITLE
Give the Symbol widget a better interface in Designer for specifying the images to use

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#374]
Right now you have to type in a JSON dictionary like {"0": "file1.svg", "1": "file2.svg"}.  This is pretty hard for normal users, who often don't know anything about JSON.  There should be a designer extension that provides a nicer graphical interface to do this.

**Comment by hhslepicka** [comment]
Awesome idea! 
Whoever implements this, consider adding a preview of the image for users!
That would be really nice.
