### ISSUE TITLE
Add support for Bar Graph at Time Plot and Waveform Plot

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#375]

**Comment by domitto** [comment]
This would be a really great feature for RGA Bar plots!
Use case: https://www.hidenanalytical.com/wp-content/uploads/2016/07/BNL-RGA-EPICS-integration-for-control-on-beamline_EPICS-INTERFACE-AND-CONTROL-OF-NSLS-II-RESIDUAL-GAS_ICALEPCS2013_Proceedings_EPIC_UDA.pdf
