### ISSUE TITLE
QUESTION: PV math calculation and boolean comparison 

### ISSUE THREAD

**Issue by q563798715** [slaclab/pydm#383]
this is a visibility PV
CALC\{A=0&&B=0C=0?1:0}{DIOD:FEE1:026:POSITION,DIOD:FEE1:426:POSITION,DIOD:FEE1:526:POSITION}
visible if >=1 and < 2
if all the three PVs = 0, the shapes are visible, otherwise not visible. 
it is used inside the red crosses and red rectangles under RTCL and DIOD in undulator map.

CALC\{15-A}{STEP:FEE1:454:MOTR.RBV}
"It takes the value of the STEP PV and does (value-15)  and that is the value used by be Bar widget." 
this is an readback PV. It is giving the widget an offset

**Comment by hhslepicka** [comment]
@q563798715 that is already possible with the `Rules`. 

**Case 1:**
You just need to add the 3 PVs to the Channels box, mark all of them as triggers...
And use: `ch[0]==0 and ch[1] == 0 and ch[2] == 0` as your expression.

**Case 2:**
visible if >=1 and < 2
Add the PV to the channels list, mark it as trigger.
Expression as: `ch[0] >= 1 and ch[0] < 2`

**Case 3:**
Do you want to make this the value of the PV? 
If yes, I would recommend to add this calculation to a CALC PV on EPICS and use this PV as the channel for the widget.
We don't support calculations on the channel yet but you can achieve that by writing some code.
