### ISSUE TITLE
Dual group behavior in Plugin Factory

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pydm#422]
**Describe the bug**

There is a function named `group()` on the factory but `self.group` is overwritten in `__init__`. Seems to work fine, but slightly confusing that this is a method overwritten as an attribute

https://github.com/slaclab/pydm/blob/837f8d546c06cc390e5d05fca418eb9ea552db68/pydm/widgets/qtplugin_base.py#L128

**Expected behavior**

```python
def group(self):
   return self._group
```

**Comment by hhslepicka** [comment]
Solved by #423
