### ISSUE TITLE
TimePlot's plot_redrawn_signal isn't triggered in Synchronous drawing mode

### ISSUE THREAD

**Issue by hmbui** [slaclab/pydm#442]
**Describe the bug**
TimeChart relies on the plot_redrawn_signal to evaluate whether a PV is active or not. See:

https://github.com/slaclab/timechart/blob/f75e7fa8502e8d605a7aa8fb5376f89e21915bba/timechart/displays/main_display.py#L104

https://github.com/slaclab/timechart/blob/f75e7fa8502e8d605a7aa8fb5376f89e21915bba/timechart/displays/main_display.py#L1149

This signal is triggered when TimePlot calls redrawnPlot:

https://github.com/slaclab/pydm/blob/293ceecc190c74deecf2134009a7cef049e87735/pydm/widgets/timeplot.py#L485

The problem is redrawnPlot is called by the redrawTimer, which isn't a part of the synchronous drawing.

**Expected behavior**
TimePlot should emit a signal when the plot is updated, i.e. live data is coming in so that a client of TimePlot, such as TimeChart, can verify whether a PV is live.

**Steps to Reproduce**
1. Run TimeChart
2. Type in a bogus PV name, like "abc"
3. See that the PV name and the Modify and Focus buttons are grayed out in the default Asynchronous charting mode
4. Change TimeChart's charting mode to Synchronous
5. Type another bogus PV name to TimeChart, e.g. "def"
6. See that the PV name and the two buttons mentioned above are not disabled.

**Possible Solution**
No workaround.

**My Platform**
Linux
macOS

**Additional context**

**Comment by mattgibbs** [comment]
> The problem is redrawnPlot is called by the redrawTimer, which isn't a part of the synchronous drawing.

This isn't correct.  The redraw_timer is always running, no matter which mode you are in.  In synchronous mode, the _update_timer_ doesn't run.

However, `plot_redrawn_signal` won't fire unless at least one curve emits its `data_changed` signal, and in your example, neither should.  Why then, does the first curve get greyed out?  It is arguably a bug in TimePlot: the first time `redraw_timer` fires, it the plot *always* redraws, and emits `plot_redrawn_signal`.  I should probably actually fix that, which would unfortunately make your example above even more broken.

TimeChart should probably handle connection state a little bit differently.  When you first add a new PV, it should start out in the disconnected state, with the buttons disabled.  Then, in `update_curve_data` in TimeChart, determine if each curve is connected using curve.connected (which is more robust than trying to guess with np.isnan), and if it is, enable the buttons.
