### ISSUE TITLE
PyDM widget for MEDM's related display menu button 

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#464]
**What's the problem this feature will solve?**
There is no PyDM widget that matches [MEDM's Related Display](https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#RelatedDisplay) menu button .

**Describe the solution you'd like**
A button that provides a pop-up menu with a choice from many related display configurations.

Since this is used extensively in synApps (such as in the [motor](https://github.com/epics-modules/motor) module and also the [green button screen](https://github.com/epics-modules/xxx/blob/master/xxxApp/op/adl/xxx.adl) in the [xxx](https://github.com/epics-modules/xxx) module), it is important to add to PyDM.  

Here's an example view from a synApps 5.8 "xxx" IOC (named *prj*) showing the pop-up menu selections:

![xxx-green-button-screen](https://user-images.githubusercontent.com/2279984/51790321-20f14700-2159-11e9-85db-634412c93bb9.jpg)

**Additional context**

Similar to the `caRelatedDisplay` widget in [*caQtDM*](http://epics.web.psi.ch/software/caqtdm/).

Also mentioned in https://github.com/BCDA-APS/adl2pydm/issues/11

**Comment by mattgibbs** [comment]
Thanks for filing this Pete.  You aren't alone, @klauer wants the same thing in issue #99.  I'll try to get something together...

**Comment by prjemian** [comment]
Thanks @mattgibbs .  You can close this issue with a *Duplicate* label.  Implementation with QPushButton as superclass is the route taken by caQtDM.
