### ISSUE TITLE
PyDMImageView has Channel that explodes

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pydm#466]
**Describe the bug**

PyDMImageView has `image_channel` and the base `channel`. If you are in QtDesigner and type anything in the `channel` field the whole thing crashes. This is a problem for new users and old users alike.

```python
Traceback (most recent call last):
  File "/Users/trendahl/Projects/sandboxes/typhon/pydm/pydm/widgets/base.py", line 828, in channel
    for channel in [c for c in self._channels if
  File "/Users/trendahl/Projects/sandboxes/typhon/pydm/pydm/widgets/base.py", line 829, in <listcomp>
    c.address == self._channel]:
AttributeError: 'NoneType' object has no attribute 'address'
```
**Expected behavior**

`PyDMImageView` uses `image_channel` 

**Steps to Reproduce**

1. Open QtDesigner
2. Drag in a PyDMImageView
3. Type in the `channel` field

**Possible Solution**
 
`channel.designable = False`

**My Platform**

MacOS
PyDM > `v1.6.5`

**Comment by klauer** [comment]
💥

**Comment by hhslepicka** [comment]
:feelsgood:

**Comment by mattgibbs** [comment]
This should probably be addressed as part of my (half-finished and forgotten PR #425).  The core problem is that the PyDMWidget base class defines a 'channel' property, when in reality not every widget uses it.

**Comment by hhslepicka** [comment]
Maybe it was used for more than what it should be.. ;)
