### ISSUE TITLE
Bug In Crosshair feature

### ISSUE THREAD

**Issue by fernandohds564** [slaclab/pydm#503]
**Describe the bug**
I get segmentation fault when I disable the crosshair in `PyDMTimePlot`.

**Expected behavior**
Enable and disable crosshair without errors.

**Steps to Reproduce**
Using the application timechart is the most simple way to reproduce the error. We just have to enable and disable the checkbox.

**Possible Solution**
The problem is related to `pyqtgraph`. There is a bug in the `disconnect` method of `SignalProxy` for which I have made a PR to fix:  pyqtgraph/pyqtgraph/pull/971.

One possible solution to this problem, which is independent of the the bug fix in pyqtgraph, is to do not call the disconnect method of `SignalProxy`, reproducing inside `BasePlot.enableCrosshair ` what is done by that method, without the bug.

**My Platform**
- OS Version: Ubuntu 18.04
- Python v3.6.8,
- Numpy v1.15.0,
- PyQt v5.11.3,
- Qt v5.11.3,
- PyQtGraph v0.10.0

**Additional context**
If you guys think the solution I proposed is appropriate, I can make a PR to implement it.

Thanks!

**Comment by hhslepicka** [comment]
Hi @fernandohds564 thank you for reporting this.
Yes, please send a PR with the bug fix and we can merge that in.
The `pyqtgraph` release is near but it will still take a while to get it.

**Comment by fernandohds564** [comment]
Hi @hhslepicka , I've created the PR #507 to solve this issue.
Thank you!

**Comment by hhslepicka** [comment]
Solved with #507
