### ISSUE TITLE
Add DataKeys.TIMESTAMP in pydm 2.0

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#518]
It should be possible to propagate timestamp information to widgets.

Consideration for timestamp metadata (like pulse ID) may be advisable as well.

**Comment by mattgibbs** [comment]
I have heard repeated requests in the past to somehow display the timestamp related to the data shown on a widget (via hover tooltip or right click or something like that).  The demand is out there!

**Comment by hhslepicka** [comment]
Reopening as we still plan to implement that.

**Comment by slactasha** [comment]
I would like to see this, and was wondering if it could simply be a special type of PYDMLabel widget (PYDMTimeLabel?)

**Comment by mattgibbs** [comment]
I'm not sure that `.TIME` is universally available, I think only certain well-behaved IOCs support it.  However, *all* monitor events come with a timestamp (if you use the right monitor flags).  We could (should?) implement the capability for handling timestamps (and passing them along to widgets) at the data plugin level.

**Comment by YektaY** [comment]
This feature was included in PR #911
