### ISSUE TITLE
If you set a stylesheet with --stylesheet, it doesn't get applied to new windows

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#551]
If I launch PyDM with the --stylesheet argument, then click a related display button that opens a new window, the new window doesn't get the stylesheet.  That's probably because the PyDM application doesn't pass that command line argument to the new PyDM process.

**Comment by ivany4** [comment]
@mattgibbs , exactly, the root of the problem lies in `PyDMApplication.new_pydm_process()`. Not only `--stylesheet` argument does not get passed, so do `--perfmon`, `--log_level` and `--read-only` flags.
