### ISSUE TITLE
Bug in PyDMWaveformPlot to show PVs with constant values

### ISSUE THREAD

**Issue by anacso17** [slaclab/pydm#556]
**Describe the bug**
PyDMWaveformPlot does not plot data if it receives X Waveform after Y when these PVs have constant values. 

**Expected behavior**
When PVs have constant values, I expected a constant waveform to be ploted in PyDMWaveformPlot, regardless of the order that PVs connect.

**Steps to Reproduce**
1) Modify the `pydm-testing-ioc` 'Waveform' variable to generate a constant, removing the additional noise in line 114:
```
- data = AMPLITUDE * numpy.sin(timeWave * FREQUENCY * 2 * numpy.pi) + (noiseAmplitude * numpy.random.random(MAX_POINTS))
+ data = AMPLITUDE * numpy.sin(timeWave * FREQUENCY * 2 * numpy.pi) # + (noiseAmplitude * numpy.random.random(MAX_POINTS))
```
2) Run the following script to create a simple window with a PyDMWaveformPlot;
```
import sys
from qtpy.QtWidgets import QWidget, QHBoxLayout
from pydm import PyDMApplication
from pydm.widgets import PyDMWaveformPlot


class TestWaveform(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setLayout(QHBoxLayout())
        self.wav = PyDMWaveformPlot(
            parent=self,
            init_y_channels='MTEST-1:Waveform',
            init_x_channels='MTEST-2:TimeBase')
        self.layout().addWidget(self.wav)


app = PyDMApplication()
wid = TestWaveform()
wid.show()
sys.exit(app.exec_())
```
3) Run first an instance of pydm-testing-ioc with prefix 'MTEST-1' to connect Y channel, and then run a second instance of pydm-testing-ioc with prefix 'MTEST-2'.

**Possible Solution**
The PR #557 has a simple solution to this bug.

**My Platform**
    * Ubuntu 18.04;
    * Python v3.6.8;
    * PyDM v1.7.3+13.g091d9778;
    * Numpy v1.15.0;
    * PyQt v5.11.3;
    * Qt v5.11.3;
    * PyQtGraph v0.10.0;

**Comment by mattgibbs** [comment]
Fixed in #558.
