### ISSUE TITLE
describe the Waveform Curve Editor in the Sphinx docs

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#571]
Skip [ahead to this point](https://github.com/slaclab/pydm/issues/571#issuecomment-553005434) since this issue was previously named as a BUG.

**Describe the bug**

Just after entering PVs to be plotted in the PyDMTimePlot widget *curves* property editor, an exception trace is printed to the console when the dialog's *OK* button is pressed.  The console output:

```
(bluesky-pydm) mintadmin@mint-vm:~/.../eclipse/pydm$ Error parsing curve json data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/mintadmin/Documents/eclipse/pydm/pydm/widgets/timeplot.py", line 544, in setCurves
    new_list = [json.loads(str(i)) for i in new_list]
  File "/home/mintadmin/Documents/eclipse/pydm/pydm/widgets/timeplot.py", line 544, in <listcomp>
    new_list = [json.loads(str(i)) for i in new_list]
  File "/home/mintadmin/Apps/anaconda/envs/bluesky-pydm/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky-pydm/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mintadmin/Apps/anaconda/envs/bluesky-pydm/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Also, no "curves" PVs are present in the .ui file:

```
   <property name="curves">
    <stringlist/>
   </property>
```

**Expected behavior**

Expected 5 different PVs to be added to *curves* property of .ui file.
The curves expected are shown in this screen shot before the exception trace from the designer session.

![Clipboard01](https://user-images.githubusercontent.com/2279984/68691961-3f82cc00-053a-11ea-9a21-16091edcfc40.jpg)

**Steps to Reproduce**

1. start Qt designer
1. Create a new window (dialog)
1. create and select a PyDMTimePlot widget
1. click *Change String List* button of the *curves* property
1. enter a few PV names (click *New* button, enter PV name, repeat a few times)
1. click *OK* button - this produces the exception trace
1. save the .ui file
1. open .ui file in an editor and search for test: `property name="curves"` - none of the PVs are present

**Possible Solution**
?

**My Platform**

* linux mint OS
* Qt designer from Qt 5.9.7
* pydm from today's master branch (1.7.3+70.g35aeb22f)

**Additional context**
looking at latest code for the new X & Y axis labels feature (much thanks for the work on #566 and #570)

**Comment by prjemian** [comment]
Same behavior when only one PV is entered.  So it's not a multi PV problem

**Comment by prjemian** [comment]
Here's the .ui file: 
[timeplot.ui.txt](https://github.com/slaclab/pydm/files/3837337/timeplot.ui.txt)

**Comment by prjemian** [comment]
No such exception trace from the PyDMScatterPlot widget.

**Comment by prjemian** [comment]
`<sound_of_palm_smacking_forehead />`

Yikes, now I realize.

Don't use the property editor for that since it expects a JSON string.  There is a special editor for the *curves* property since it is complex.

1. Right clock on the PyDMTimePlot widget for special menu
1. Select *Edit Curves...*
1. Resume proceeding on your own intuition ...

**Comment by prjemian** [comment]
Since this was not my intuitive first choice, I suggest to make that same *Waveform Curve Editor* appear for this action: "4. click *Change String List* button of the curves property"

If power users want access to edit raw json within the designer session, then a button to provide that access can be added to the *Waveform Curve Editor*.

**Comment by mattgibbs** [comment]
Totally agree that the 'curves' property is basically a landmine, waiting to explode on helpless display authors.  We unfortunately can't change the behavior of Designer very much.  What we _could_ do is hide the 'curves' property entirely, and maybe add a bit of text to the plot that encourages the user to double click it to edit curve properties.

Do you think that would be sufficient?

**Comment by prjemian** [comment]
Good for me.  I stepped in the *pot hole* (it's that season here) of the *curves* property editor.

**Comment by prjemian** [comment]
Most important support for this is to describe the  *Waveform Curve Editor* in the Sphinx docs.  Right now, it has zero [cross-section](https://www.nuclear-power.net/nuclear-power/reactor-physics/nuclear-engineering-fundamentals/neutron-nuclear-reactions/definition-of-cross-section/) for a [search](http://slaclab.github.io/pydm/search.html?q=Waveform+Curve+Editor&check_keywords=yes&area=default).

**Comment by prjemian** [comment]
["pot hole"](https://duckduckgo.com/?ratb=c&q=pot+hole%2C+pittsburgh+bus&t=ffsb&iax=images&ia=images)

**Comment by prjemian** [comment]
renaming this issue now
