### ISSUE TITLE
PyDMTimePlot time axis shows extra (x1e+09) text

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#572]
With today's master branch (1.7.3+70.g35aeb22f), the PyDMTimePlot widget's 
time axis shows this extra text after the label: `(x1e+09)`
![Clipboard01](https://user-images.githubusercontent.com/2279984/68698698-1d437b00-0547-11ea-9551-9b1f3107acf8.jpg)

Since the axis is formatted to show time as HH:MM:SS, display of this large offset in the current time's unformatted integer value provides no additional value.  It just makes the screen more cluttered.

Can this be suppressed from display?  Easily?  Seems like a special case but it is common.

**Comment by prjemian** [comment]
Confirmed this is a fix.  Thanks!

**Comment by hhslepicka** [comment]
Awesome! Thanks @prjemian ... 
Please keep the issues coming! 👍
