### ISSUE TITLE
PyDMByteIndicator: bigEndian ignored in Horizontal orientation

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#576]
**Describe the bug**
Displaying a mbbo record (4 bits) using the PyDMByteIndicator widget, when *orientation* property is `Horizontal` and *bigEndian* property is `True` (as shown in the screen below), the widget displays the same as the one above it, which has *bigEndian* unchecked (`False`).

Note the error appears in the designer and in the PyDM application.

**Expected behavior**
Expected to see the bit patterns as shown in the MEDM window (left of the PyDM window in the attached screen shot).

**Steps to Reproduce**
As explained.  Here's the screen shot with Qt Designer and incorrect widget selected, showing the properties' values.  Also shows MEDM (black and grey widgets) and PyDM (green and grey widgets) for comparison.
![Clipboard01](https://user-images.githubusercontent.com/2279984/68794438-9f4da580-0614-11ea-8846-c8062ed0985b.jpg)

**My Platform**
master branch as pulled yesterday: 1.7.3+70.g35aeb22f

**Comment by hhslepicka** [comment]
Working on a fix for that...
