### ISSUE TITLE
need PyDMShellCommandList widget

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#581]
**What's the problem this feature will solve?**
Allows translation of MEDM's [*shell command*](https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#ShellCommand) widget.

**Describe the solution you'd like**
Similar to [*PyDMShellCommand*](https://slaclab.github.io/pydm/widgets/shell_command.html), this is a button.  But, it is a pop-up menu with a *list* of shell commands.

**Additional context**
https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#ShellCommand

**Comment by mattgibbs** [comment]
For the Related Display Button, we changed the 'display' property from a QString to a QStringList, and if there was a single display in the list, it works like a normal button.  If there are multiple displays, it gives you the pop-up menu.

I think I'd rather do that for the Shell Command button too, to maintain parity with how Related Display Button works.  Would that solution be OK?

**Comment by prjemian** [comment]
That's great!

**Comment by prjemian** [comment]
the pop-up menu items each have a label
