### ISSUE TITLE
PyDMLabel widget displays waveform string as array of int

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#586]
**Describe the bug**

Constructing a screen to display live images from EPICS AreaDetector.  Some of the content uses the pattern of a long string constructed from a waveform record of DBF_CHAR.  This is to display strings that could be longer than the length of the stringout record.

The `PyDMLabel` widget shows the PV content as array of integers.

**Expected behavior**

We expect to see the array of integers rendered as a string, such as in the caQtDM window in the attached screen image.  Compare these results using command line `caget`:

```
(bs) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ caget -S adsky:cam1:StatusMessage_RBV
adsky:cam1:StatusMessage_RBV Acquisition stopped
(bs) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ caget adsky:cam1:StatusMessage_RBV
adsky:cam1:StatusMessage_RBV 256 65 99 113 117 105 115 105 116 105 111 110 32 115 116 111 112 112 101 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Steps to Reproduce**

EPICS AreaDetector ADSimDetector instance, look at `${P}cam1:StatusMessage_RBV` (where `P=13SIM1:` is the default prefix.)

**Possible Solution**

**My Platform**
linux mint

**Additional context**
image of screen showing: (left) caQtDM screen, (middle) PyDM screen, (right) Qt Designer, (lower) terminal session:

![Clipboard01](https://user-images.githubusercontent.com/2279984/70569259-3a2b9800-1b5f-11ea-968d-79f107b0153c.jpg)

```
(bs) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ cainfo adsky:cam1:StatusMessage_RBV
adsky:cam1:StatusMessage_RBV
    State:            connected
    Host:             mint-vm:44307
    Access:           read, write
    Native data type: DBF_CHAR
    Request type:     DBR_CHAR
    Element count:    256
(bs) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ caget adsky:cam1:StatusMessage_RBV.RTYP
adsky:cam1:StatusMessage_RBV.RTYP waveform
```

**Comment by hhslepicka** [comment]
@prjemian please try to set the `displayFormat` of this `PyDMLabel` to `String`

**Comment by prjemian** [comment]
Perfect.  Temporary blindness.
