### ISSUE TITLE
Some PyDM widgets lose their native look

### ISSUE THREAD

**Issue by ivany4** [slaclab/pydm#587]
**Description**
PyDMEnumComboBox and PyDMLineEdit lose their native style. I have also encountered this behavior when creating my own QPushButton subclass. As soon as I inherit from PyDMWidget, the style breaks.

**Expected behavior**
Look stays unchanged for widget, unless specificaly altered via stylesheet.

**Steps to Reproduce**
1. Drag any of those widgets in Qt Designer onto the form
2. While dragging, widget appears to have the correct look
3. Once dropped on the form, widget changes its look and becomes "flat"
4. When running PyDM app, these widgets are flat.

**My Platform**
* OS Version: Ubuntu 18.04/Gnome; CentOS7/Xfce
* Python version: 3.6.5
* Package Version (Latest master (1.8)), but I remember always seeing this bug, since 1.5

**Comment by hhslepicka** [comment]
Can you try running the same file with PyDM but passing in an empty stylesheet file?
That is probably due to the border property that comes with the default_stylesheet

**Comment by ivany4** [comment]
@hhslepicka , yes indeed, that solves the problem

**Comment by ivany4** [comment]
OK, got it! so alarmSensitiveBorder=True makes all widgets to have transparent border and it is set to True by default.

**Comment by hhslepicka** [comment]
That is due to the fact that we are setting the default border to transparent... it is a tricky piece since some widgets like buttons have OS default behavior... I will take a look at it later today and think about a way to even with alarmSensitiveBorder make it not be like that
