### ISSUE TITLE
[Learning] How do you debug designer plug-in?

### ISSUE THREAD

**Issue by 625781186** [slaclab/pydm#595]
1. Manually restart `designer. exe` after every plug-in change?

2. 
I load the plug-in this way, 
But I can't get any error when my plugin goes wrong.

![image](https://user-images.githubusercontent.com/30521429/74101256-e21b0d00-4b72-11ea-81c8-e4fe56ac6b12.png)

I hope to get some useful advice from you. Thank you.

**Comment by hhslepicka** [comment]
Hi @625781186 ,
Which type of plugin do you want to debug?
A new widget? New Data Plugin?
With that maybe we can provide better insight on how to debug.

**Comment by 625781186** [comment]
> Hi @625781186 ,
> Which type of plugin do you want to debug?
> A new widget? New Data Plugin?
> With that maybe we can provide better insight on how to debug.

What's the difference?
I'm mostly customizing new widgets.

**Comment by 625781186** [comment]
@hhslepicka
Hello ? 
https://github.com/slaclab/pydm/issues/595#issuecomment-586800366

**Comment by klauer** [comment]
@625781186 are you using PyDM or are you after general PyQt + designer help?

**Comment by hhslepicka** [comment]
@ 625781186 you will never going to get the exception at PyCharm due to the fact that it happens at the `Designer.exe` process. We test our widgets, data plugins and overall Qt plugins here as described in number 1 and via automated test. I'm closing this issue as it is not related to PyDM.

**Comment by 625781186** [comment]
> @625781186 are you using PyDM or are you after general PyQt + designer help?
@klauer 
I think it's a general PyQt + designer help.
