### ISSUE TITLE
control button spacing and margins in PyDMEnumButton

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#605]
**What's the problem this feature will solve?**

Many screens to be converted from synApps use a group of buttons to provide access to enum values.  The `PyDMEnumButton` fits this design.  The model that maps MEDM screens to PyDM needs to be able to control the spacing between buttons and margins around the button group (optionally set all to some non-negative integer) to fit the prescribed widget geometry.

**Describe the solution you'd like**
Add additional property values to `PyDMEnumButton` to set margins (left, right, top, bottom) and spacing (horizontal, vertical).  The default values should be as provided by the `QGridLayout` used in the `PyDMEnumButton` code.  The defaults would be defined and values set in the constructor.

**Additional context**
The [Qt documentation for `QGridLayout`](https://doc.qt.io/qt-5/qgridlayout.html) says *The default contents margin values are provided by the style.*  I tried setting these values in the widget's style sheet (following the [style sheet](https://doc.qt.io/qt-5/stylesheet-reference.html) list of properties) with no effect.

```
   margin: 0px;
   padding: 0px;
   spacing: 0px;
```

The effective remedy was to alter the `pydm.widgets.enum_button.PyDMEnumButton.__init__()` code, adding:

```
    self.setLayout(QGridLayout(self))
    self.layout().setHorizontalSpacing(0)
    self.layout().setVerticalSpacing(0)
    self.layout().setContentsMargins(0,0,0,0)
```

The zero values are for demonstration.  We should make these into additional properties.  The margin can be described by [`QMargins`](https://doc.qt.io/qt-5/qmargins.html).

Compare with this screen shot.  On the left is the converted PyDM screen setting spacing and margins to zero, on the right is the MEDM original.

**Comment by hhslepicka** [comment]
@prjemian the screenshot is missing

**Comment by prjemian** [comment]
![Clipboard01](https://user-images.githubusercontent.com/2279984/76687873-e7e29300-65f5-11ea-9ccb-ea6b4d5177aa.jpg)

**Comment by prjemian** [comment]
How to specify a [QMargins](https://doc.qt.io/qt-5/qmargins.html) object as a `@Property` so the designer shows the top, bottom, left, and right?  Don't believe there is an editor for that by default.  Will make the components into Property entries: `margin_top`,  `margin_bottom`,  `margin_left`, and  `margin_right`.
