### ISSUE TITLE
support for long string suffix: $

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#607]
**Describe the bug**
While developing code to convert MEDM screen files to PyDM, noticed that the long string suffix `$` results in a display of *array of int* rather than a string rendering.

![Clipboard01](https://user-images.githubusercontent.com/2279984/76873723-1f428100-683c-11ea-96f4-1e16fe52292e.jpg)

**Expected behavior**
A PV that ends with `$` should be displayed as a string.
![Clipboard02](https://user-images.githubusercontent.com/2279984/76873850-54e76a00-683c-11ea-892d-41b8658ef68b.jpg)

**Additional context**
This support was added in EPICS base 3.14.12 and appears in the [Release Notes](https://epics.anl.gov/base/R3-14/12-docs/RELEASE_NOTES.html) (not sure if it appears anywhere else, maybe tech-talk).  Look for the section marked *Long string support* (there is no anchor available in the doc).

This is quote from an email conversation with @anjohnson about the `$` suffix:

> Adding a trailing $ sign to a string field name (or ending ‘.$’ to mean .VAL$) tells the IOC that you want it to modify the data type reported up to CA server code for this channel to make it an array of characters, which allows the CA protocol to transmit strings that are longer than the 40 character limit of the DBF_STRING type. However you also have to configure your CA client to display that character array as a string. For caget you do that with a flag -S. For medm and CS-Studio there are format settings for the text widgets. I don’t know how PyDM does that, assuming it does support it (I would expect it to, but I don’t know).

**Comment by hhslepicka** [comment]
@prjemian please set the `displayFormat` property to String and it will be properly rendered.

**Comment by prjemian** [comment]
Like this (as designer writes it):

```
<property>
  <enum>PyDMLineEdit::String</enum>
</property>
```

![Clipboard03](https://user-images.githubusercontent.com/2279984/76878136-63d11b00-6842-11ea-8144-2042e834da5d.jpg)

That fixes it!  Thanks!
