### ISSUE TITLE
Add a 'default protocol' environment variable.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#61]
Add an environment variable where you can specify a protocol to use by default if one is not provided for a channel (i.e. if you set the default protocol to 'ca', and specify a channel with just 'MTEST:Float', PyDM will interpret it as 'ca://MTEST:Float').

**Comment by hhslepicka** [comment]
Just remember to also remove the protocol from the PVs copied by the middle click if they are the default...

**Comment by hhslepicka** [comment]
Closed by #71
