### ISSUE TITLE
"Edit in Designer" File menu item always grayed out

### ISSUE THREAD

**Issue by rreno** [slaclab/pydm#622]
**Describe the bug**
In a PyDM screen the menu item File->"Edit in Designer" is grayed out even with a valid QtDesigner binary in the path. 

A workaround is to open QtDesigner and then open the appropriate ui file manually.

**My Platform**
RHEL6 linux-x86_64 (SLAC development environment)
PyDM 1.9.0 using Python 2.7.9, Numpy 1.16.5, PyQt 5.9.2, Qt 5.9.5 PyQtGraph 0.10.0

**Comment by hhslepicka** [comment]
Thanks, @rreno . I will take a look into it right now.
