### ISSUE TITLE
Make PyDM a Python Package

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#64]
Make so PyDM can be installed.
This is already in progress and almost done...

[x] Use versioner to automatically add the version from GitHub tags and commits to the package.
[ ] Create setup method to remove the usage of ```python pydm.py my_file.ui``` when running a standalone project.
[ ] Whatever else is needed and I find while working on this...

**Comment by mattgibbs** [comment]
Fixed by #81.
