### ISSUE TITLE
Template repeater: data source could accept JSON directly

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#672]
**What's the problem this feature will solve?**
Template repeater data source does not allow direct passing of the JSON text, instead requiring a file to open.

https://github.com/slaclab/pydm/blob/1a7f50ce5962201553118b0f07b4d0078e4647cd/pydm/widgets/template_repeater.py#L291-L309

**Describe the solution you'd like**
It'd be nice if it detected that `dataSource` was JSON itself, and load it directly.

**Comment by hhslepicka** [comment]
I agree with the request, it makes sense to accept also the JSON text.
As a workaround you can use `data` and pass in a dictionary. It is a property at the widget that when set will invoke rebuild.
https://github.com/slaclab/pydm/blob/1a7f50ce5962201553118b0f07b4d0078e4647cd/pydm/widgets/template_repeater.py#L414-L422

**Comment by klauer** [comment]
Good idea - though I think that requires a Python script instead of a designer display, right?

**Comment by hhslepicka** [comment]
oooh, it was via the designer... my bad! I missed this part... in this case I agree even more with the request.

**Comment by hhslepicka** [comment]
Proposed fix is up...
