### ISSUE TITLE
PyDMEnumButton shows "Item ..." button in background

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#674]
**Describe the bug**

EPICS v3 data source with enum strings. Seems like on the first load it often shows an additional button in the background:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/5139267/89328212-e4ea4c80-d641-11ea-8576-9977e10d708a.png">

Floor and Ceiling are correct here, but "Item ..." is not.

**Expected behavior**
Only the actual enum choices should show.

Can dig into this more locally if you've never seen it before.

**Comment by hhslepicka** [comment]
I just saw this now after you reported... 
<img width="687" alt="image" src="https://user-images.githubusercontent.com/8185425/89329395-9ccc2980-d643-11ea-8e7c-d61d346fc9e0.png">

It shows the button but once the PV connects it goes away. In your case it seems like the button remains even after connection.
I will take a look into that. Thanks for the bug report.
