### ISSUE TITLE
PyDMSpinbox: Add option to change the arrow behavior and directly write the value when pressed 

### ISSUE THREAD

**Issue by jesusvasquez333** [slaclab/pydm#686]
**What's the problem this feature will solve?**
Currently, when pressing the arrows on a `PyDMSpinbox` widget you need to press `ENTER` for the value to be written to the channel (a PV in my case).

**Describe the solution you'd like**
I would add an new property to the widget called `writeOnPress` or something similar. When this option is selected, then pressing the arrows in the widget will immediately write the new value to the  channel, without having to press the`ENTER` key.

**Comment by jacquelinegarrahan** [comment]
Will this also be triggered for up/down keyboard keys in addition to the widget arrows?

**Comment by hhslepicka** [comment]
Yes. There is a signal that takes care of it without need to handle separately the up arrow and etc. take a look at the history of this widget.

**Comment by hhslepicka** [comment]
Addressed via #690.
