### ISSUE TITLE
pyqtgraph >=0.12 breaks PyDMImageView

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#731]
**Describe the bug**
Yet another breaking change from pyqtgraph and PyDMImage.
Everything works fine with 0.11 series.

**Expected behavior**
PyDMImage works fine as expected.

**Steps to Reproduce**
Update your pyqtgraph to >= 0.12 and run the examples

**Possible Solution**
- Apply a patch into PyDMImage widget after finding what is causing it.

**Comment by jbellister-slac** [comment]
I'm going to take a look at this since I was planning on using the most recent pyqtgraph version for the plotting changes
