### ISSUE TITLE
If you assign a stylesheet to any of the PyDM plotting widgets, that stylesheet gets applied to the curve editor in designer.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#734]
**Describe the bug**
If you assign a stylesheet to any of the PyDM plotting widgets (or, if a stylesheet cascades down to a PyDM plotting widget), that stylesheet gets applied to the curve editor in Qt Designer.  If you have a black background, for instance, this makes the curve editor unusable.

**Expected behavior**
Curve editor doesn't get any stylesheet applied.

**Steps to Reproduce**
Open designer, drag a PyDMTimePlot (or any plot type) onto the form.  On the top-level QWidget, set the styleSheet property to `background-color: black;`.  Now, double-click the plotting widget to open the curve editor.  The editor will have a black background.

**Possible Solution**
Set a hard-coded stylesheet on the curve editor?  Unclear if we need to do this, or just unset the styleSheet property.

**My Platform**
I tested this on PyDM 1.11.0.  I don't think it matters much for this bug, but I am on Python 2.7.13, PyQt 5.9.2, and Qt 5.9.1.

**Comment by hhslepicka** [comment]
The best practice is to always use the Widget class when doing things like that...
Here is a demonstration on how using `PyDMTimePlot {background-color: black; }` solves the issue:
![image](https://user-images.githubusercontent.com/8185425/115976115-88a4c100-a51f-11eb-86c5-b82dbce0d83c.png)

I guess it is more a problem of getting familiar with the cascading aspect of QSS. Not really a bug IMHO.

**Comment by nstelter-slac** [comment]
Issue addressed, closing.
