### ISSUE TITLE
Tab Widget default tab

### ISSUE THREAD

**Issue by scalverson** [slaclab/pydm#764]
Can we change the Tab Widget to always default to Tab 1, or maybe have a user selectable default tab at least?  

Currently it always comes up with whatever tab was set as "currentIndex" which in designer is whatever the last tab you were working on when you saved the file.  This means if you forget to toggle back to your main tab, the widget comes up wrong the next time it launches.

**Comment by YektaY** [comment]
I have gone with the simple solution of setting the default tab to 0 through the default stylesheet. The stylesheet sets the currentIndex to 0 when the widget is launched. If this solution turns out to not fully address the issue, please feel free to create a new issue! :)
