### ISSUE TITLE
PV list to clipboard

### ISSUE THREAD

**Issue by slactasha** [slaclab/pydm#799]
**What's the problem this feature will solve?**
Conveniently get all PVs on an interface to the clipboard

**Describe the solution you'd like**
Select 'Copy PV list to clipboard' from context menu

**Comment by mattgibbs** [comment]
On the menu bar, View -> Show Connections pops up a screen that shows all the PVs on a display.  This is called the "connection inspector".  It has a button to save that list to a text file, but not a way to save it to the clipboard.  I'd suggest we add a 'save to clipboard' button to the connection inspector.
