### ISSUE TITLE
Expand context menu for PyDMEmbeddedDisplay to include 'Open in New Window...'

### ISSUE THREAD

**Issue by kabanaty** [slaclab/pydm#809]
**What's the problem this feature will solve?**
Right-clicking on a PyDMEmbeddedDisplay widget at runtime will give an option to open the embedded display file in a new window.  This would act intuitively like a pop-up window.  This allows operators to customize their workflow as necessary.

**Describe the solution you'd like**
An addition to the context menu for PyDMEmbeddedDisplay widgets with the option to open a pop-up window.

**Additional context**
Similar to the existing EDM context menu functionality.

![image](https://user-images.githubusercontent.com/35951619/157735820-4cc043d3-e98f-4ccc-ba97-826cc3fc68a4.png)

**Comment by mattgibbs** [comment]
This is a good idea!
