### ISSUE TITLE
Change default text of PyDMLabel to '######'

### ISSUE THREAD

**Issue by kabanaty** [slaclab/pydm#815]
**What's the problem this feature will solve?**
Currently, when a PyDMLabel is not connected to a channel, the label will display 'PyDMLabel'.  At a glance, this can appear as if nothing is wrong.  

**Describe the solution you'd like**
Making the default text '######' will make it immediately obvious that there is no real data being displayed.

**Additional context**
Note how the current default text 'PyDMLabel' is disguised in a grid of readbacks, yet '######' is easy to see.  This difference can be enhanced with stylesheets, as well.
![image](https://user-images.githubusercontent.com/35951619/159081243-77a93a2c-1ed7-4864-b8d2-e93354187f6d.png)

**Comment by mattgibbs** [comment]
What if we show the channel name when the PV is not connected (like EDM does)?  I kind of like that feature.
—Matt

**Comment by Ryan-McClanahan** [comment]
I like this idea.  There is one issue with the proposed functionality.  Currently, the only way to apply rules to text is to us a PyDMLable.  There should be an option in the widget for custom text to be displayed if no channel is connected.

A good example of this use case at Slac is bypassed alarms.  If an alarm is bypassed further down the alarm tree then an * will appear next to the related display button.

![image](https://user-images.githubusercontent.com/93741302/161166423-01860a1e-c763-472c-a175-3df9f494bf59.png)
