### ISSUE TITLE
When a display is reloaded, pyca plugin doesn't re-send connection status or properties like units.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#86]
When you reload a display (via the File menu or hotkey), the pyca data plugin doesn't re-send connection signals or units, precision, limits, etc.

**Comment by hhslepicka** [comment]
This will probably be fixed by some changes that I did at the base widget
branch on the pyepics plugin... can you try to add a self.pv.run_callbacks
on the connection changed?

**Comment by mattgibbs** [comment]
Right after I wrote this bug I realized it was only a problem when using the pyca plugin, pyepics already works fine because it calls self.pv.run_callbacks() in the case that a listener gets added to an already-existing PV.  In the pyca plugin, it tries to not re-emit any control info unless it has changed, and that is inadvertently silencing the connection/control info from getting re-sent.

**Comment by hhslepicka** [comment]
Awesome! ;)
Does pyca offers a way to force the callbacks to run again with ctrl_vars?

**Comment by mattgibbs** [comment]
Yeah, it is pretty easy to do it, I just need to implement it in the plugin.
