### ISSUE TITLE
Reduce default plotting rate (baseplot / timeplot)

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#870]
## Preface

I'm no expert on any of these aspects of PyDM - so take the following with a grain of salt

##  Suggestion

* Reduce plotting rates: baseplot has it at 30Hz
* Reduce the default update rates for data from 10Hz in timeplot

## Reasoning

There is often little need in general to update plots at 30Hz, even if the data is updating at that rate.

We've seen issues where there are several time plot widgets in a single process dragging each other down and interfering with normal operation.

My opinion is that reducing this to something closer to 1 second would be reasonable: https://github.com/slaclab/pydm/blob/67905dba77aaff0256642a9ff044ed0c57bcf97b/pydm/widgets/baseplot.py#L572 

I think it's easy to hit the 30Hz updates if you have multiple signals in the plot updating at 10Hz (the default update interval in `timeplot`)

## But I want fast plots...

If the user wants fast updates, they can increase the update rates and accept the performance hit that comes along with it.

**Comment by jbellister-slac** [comment]
This sounds reasonable to me. Having a 1 second default and letting the user request a faster update rate makes sense to me compared to the current default.
