### ISSUE TITLE
Email group?

### ISSUE THREAD

**Issue by gabrielfedel** [slaclab/pydm#89]
Hi there,

Have you considered to create an email group for pydm?
I think questions like doubts and next steps for project could be discussed at that place. We, at LNLS, certainly participate. =)

**Comment by hhslepicka** [comment]
Hi @gabrielfedel, that is a good idea! We have an internal mailing list and SLACK channel for PyDM.
I would suggest that we go for a tool integrated with GitHub such as Gitter (http://gitter.im/) which is more dynamic and integrated with GitHub then a mailing list. What do you think about it @mattgibbs ?

**Comment by gabrielfedel** [comment]
Hi @hhslepicka , I didn't know gitter, is it possible to organize "threads" to organize subjects on it?

**Comment by hhslepicka** [comment]
@gabrielfedel I am not sure about the "threads" but I saw that it is possible to create multiple discussion rooms

**Comment by mattgibbs** [comment]
I think our mailing list should be public, and it might already be - @gabrielfedel, can you try to send an email to listserv@slac.stanford.edu with the body as follows: subscribe pydm-users.  Let me know if you get an error message.  If so, I think we can fix it.

The mailing list is OK but its really kind of a pain to have a conversation on, so yes, we should probably have some sort of real-time chat as well.  Gitter looks like a good option, lets try it out and see if it takes off.

**Comment by hhslepicka** [comment]
@gabrielfedel @mattgibbs .... I just created the "General" room using Gitter: https://gitter.im/pydm/General?utm_source=share-link&utm_medium=link&utm_campaign=share-link

We can get started with this one and evaluate the tool! The room is public!

**Comment by gabrielfedel** [comment]
Hi @mattgibbs , I tryied to send this email, but I received this message
"Your system is outside this LISTSERV's service area for the PYDM-USERS list.
Your  subscription  request   has  been  denied.  Contact   the  list  owner...

@hhslepicka I'm in gitter! ;)

**Comment by hhslepicka** [comment]
@gabrielfedel I just noticed that the list is restricted to @slac.stanford.edu emails! 
About Gitter... Awesome! I just saw you there! We can start poking around there.

**Comment by hhslepicka** [comment]
Closing this issue as we are using Gitter at least as an initial communication tool.
https://gitter.im/pydm/General
