### ISSUE TITLE
BasePlot.clear() doesn't work properly with new MultiAxisPlot.

### ISSUE THREAD

**Issue by mattgibbs** [slaclab/pydm#895]
I was trying to clear out all curves on a PyDMWaveformPlot at runtime (using `PyDMWaveformPlot.clearCurves()`, which just calls `BasePlot.clear()`), and found that a frozen version of the old curves were left behind on the plot.  It looks like the root cause is that `MultiAxisPlot` needs to re-implement `clear()` to properly remove all curves from all of its viewBoxes.

**Comment by jbellister-slac** [comment]
Thanks for reporting! Good news is a simple fix that I was testing for a different issue should fix this too. Will put up a PR shortly.
