### ISSUE TITLE
PyDMTimePlot's y-axis displays entire data range even though 'Visible Data Only' is checked

### ISSUE THREAD

**Issue by physwkim** [slaclab/pydm#924]
**Describe the bug**
From PyDM v1.15.1, Auto-range on visible data is not working for PyDM. The y-axis displays the entire date range.

![Screenshot from 2022-09-22 15-52-19](https://user-images.githubusercontent.com/51432966/191678895-4d20f3de-a34b-4bfa-9883-372e7ebb4168.png)

**Expected behavior**

The Y range need to be adjusted to fit the visible data. If 'Visible Data Only' is checked.
![Screenshot from 2022-09-22 15-50-52](https://user-images.githubusercontent.com/51432966/191678394-967615e8-01bf-4c30-8a85-93aa2e6349bf.png)

**Comment by jbellister-slac** [comment]
Hi, thanks for reporting this! We will get a fix in for the next release.

In the mean time, there is a work around. Clicking directly near the y-axis to bring up the menu instead of the area with the data will cause it to work as expected as in the image below. Just a temporary work around though, will make sure it works no matter where you click in the next release.

![plot](https://user-images.githubusercontent.com/89539359/191868938-6eed63c0-d422-4a99-beee-f95847f17dc7.gif)

**Comment by physwkim** [comment]
The method you mentioned also works well.
From v1.15.1, it seems that two ViewBox instances are created as show below.  

```python
In [1]: # %load pydmtimeplot.py
   ...: from silx.gui import qt
   ...: from pydm.widgets import PyDMTimePlot
   ...:
   ...:
   ...: wg = qt.QWidget()
   ...: wg.setLayout(qt.QVBoxLayout())
   ...:
   ...: timeplot = PyDMTimePlot()
   ...: timeplot.addYChannel(y_channel='ca://BL8C:signal0')
   ...: print(f"axes : {timeplot.plotItem.axes}")
   ...: wg.layout().addWidget(timeplot)
   ...: wg.show()
axes : {'top': {'item': <pyqtgraph.graphicsItems.AxisItem.AxisItem object at 0x7fb675ed9280>, 'pos': (1, 1)}, 'bottom': {'item': <pydm.widgets.timeplot.TimeAxisItem object at 0x7fb676fda670>, 'pos': (3, 1)}, 'right': {'item': <pyqtgraph.graphicsItems.AxisItem.AxisItem object at 0x7fb675ed43a0>, 'pos': (2, 2)}, 'left': {'item': <pydm.widgets.basepl
ot.BasePlotAxisItem object at 0x7fb675ef0a60>, 'pos': None}}

In [2]: from pyqtgraph import ViewBox

In [3]: list(ViewBox.AllViews.keys())
Out[3]:
[<pydm.widgets.multi_axis_viewbox.MultiAxisViewBox at 0x7fb675f3baf0>,
 <pydm.widgets.multi_axis_viewbox.MultiAxisViewBox at 0x7fb675ef0b80>]

In [4]: timeplot.plotItem.vb
Out[4]: <pydm.widgets.multi_axis_viewbox.MultiAxisViewBox at 0x7fb675f3baf0>
```

https://github.com/slaclab/pydm/blob/f4224d9bfc4caa6e72fc79796f31ff7e8078315b/pydm/widgets/multi_axis_plot.py#L87

As far as I know, it could to be solved by linking to the first ViewBox.
```python
axis.linkToView(self.vb)
```

**Comment by jbellister-slac** [comment]
Correct, multiple view boxes were added then. And that would work for this case in which there is only one y-axis. But the reason that v1.15 added multiple view boxes was to support multiple y-axes on the same plot - the multiple view box solution seemed the least painful way of getting it to work with pyqtgraph. So linking to the first view box here would cause issues when trying to add additional axes to the plot.

For this case I think I will add a few options to the view box menu, and fix a separate issue where the menus for the additional views are being set incorrectly. Should have the fix up tomorrow!
