### ISSUE TITLE
Tests fail with pyqtgraph 0.13

### ISSUE THREAD

**Issue by canismarko** [slaclab/pydm#928]
I'm planning on submitting a PR, but before I did I wanted to make sure I could get the tests to pass on the master branch. Following the instructions in the readme, I get 9 failed tests with the same error. With pyqtgraph 0.12.4 the tests all pass.

**Describe the bug**

I get the following error when running the tests:

> E       AttributeError: 'WaveformCurveItem' object has no attribute 'setPointMode'
> 
> pydm/widgets/multi_axis_plot.py:181: AttributeError

where the object listed is either WaveformCurveItem or TimePlotCurveItem.

**Expected behavior**

I expect the tests to pass.

**Steps to Reproduce**

Created a new conda environment, installed dependencies, and ran the tests according to the readme file.

> mamba create -n pydm python=3.9
> mamba activate pydm
> mamba list | grep pyqtgraph
> pip install -r requirements.txt -r dev-requirements.txt PyQt5
> python run_tests.py

**Possible Solution**
 

I don't know what the setPointMode() method does. Perhaps the call can just be removed from pydm? If I comment out pydm/widgets/multi_axis_plot.py line 181 then the tests all pass.

In the pyqtgraph 0.12.4 code there's a commented deprecation warning in the setPointMode method:

> warnings.warn(
>         #     'setPointMode has been deprecated, and has no effect. It will be removed from the library in the first release following April, 2022.',
>         #     DeprecationWarning, stacklevel=2
>         # )

https://github.com/pyqtgraph/pyqtgraph/blob/cd855bd79b22476d6de3211cf57150abbe7edf5b/pyqtgraph/graphicsItems/PlotDataItem.py#L468

and it was removed in this commit at the end of August: https://github.com/pyqtgraph/pyqtgraph/commit/b2e1c0e9dec0d6b04655d85c53fd510ab5f3d58e#diff-a2b5865955d2ba703dbc4c35ff01aa761aa28d2aeaac5e68d24e338bc82fb5b1

**My Platform**

RHEL9 using mamba for environment and package management.

Tested with both python=3.9.13 and python=3.10.

Numpy: 1.23.3
PyQt: 5.15.7
Qt: 5.15.2
PyQtGraph: 0.13.1

Kernel: Linux s9dhcp137.xray.aps.anl.gov 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Mon Jun 6 15:05:22 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

There are several other failed tests and errors, but they also pass when I downgrade to pyqtgraph 0.12. In case it helps, here's the full pytest report: https://gist.github.com/canismarko/d0c06db63056bf1b572869189fd58eb0

**Comment by jbellister-slac** [comment]
Hi, thanks for reporting this! I just ran into it myself the other day, tacked a fix onto my other plot PR (just removing that call is the right solution). I'll try and get that merged in today, or maybe break it out into its own PR if needed to get tests working again. Apologies for the inconvenience, if you'd like you can still open your PR now and we'll just ignore those tests since everything passes when you comment out that line.
