### ISSUE TITLE
[Label] Units

### ISSUE THREAD

**Issue by laispc** [slaclab/pydm#93]
Hi,

1) Property 'showUnits' seems to be ignored. No matter its value, units are always shown.
2) If precision is zero and _units_string != "", then only units are shown (value is missing).

I'm attaching a test ui.
Thanks,
Laís

[iss_label_showUnit_0.3.0.zip](https://github.com/slaclab/pydm/files/1249646/iss_label_showUnit_0.3.0.zip)

**Comment by hhslepicka** [comment]
Closed by #94 .
