### ISSUE TITLE
Add notes to rules

### ISSUE THREAD

**Issue by Ryan-McClanahan** [slaclab/pydm#937]
**What's the problem this feature will solve?**
It can be difficult to determine what the intention of a rule on a widget is sometimes.  It would be nice to add a notes field to the rules menu so a description of what a rule does can be added

**Comment by nstelter-slac** [comment]
hi, 
initial change up here: https://github.com/slaclab/pydm/pull/1026

**Comment by nstelter-slac** [comment]
https://github.com/slaclab/pydm/pull/1026
