### ISSUE TITLE
Widgets categories

### ISSUE THREAD

**Issue by laispc** [slaclab/pydm#95]
Hi,
The list of widgets is getting large and Designer loads them in random order. Sometimes it is difficult to quickly find one of them. So it would be interesting to create subcategories. E.g.: monitors, controls, plot, drawing etc.
Icons (#44) will make it easier to find a widget, but categories would make it even more organized.

Maybe the **group name** of a widget can be passed as argument in **qtplugin_factory**?
Thanks,
Laís

**Comment by hhslepicka** [comment]
👍 to separating the widgets in categories...
@laispc would you mind to put a PR to make group be instead of a hardcoded "PyDM Widgets" something from a parameter with "PyDM Widgets" being the default?
See https://github.com/slaclab/pydm/blob/master/pydm/widgets/qtplugin_base.py#L94

**Comment by laispc** [comment]
Okay! :)
