### ISSUE TITLE
Setting PyDMByteIndicator circles to true crashes designer

### ISSUE THREAD

**Issue by aswyatt** [slaclab/pydm#957]
**Describe the bug**
When inserting the byte indicator and setting it to circle, designer crashes

**My Platform**
- Ubuntu 22.04.1 LTS (Jammy Jellyfish) x86_64
- Python 3.10.8
- Numpy 1.24.1
- PyQt 5.12.3
- Qt 5.12.9
- PyQtGraph 0.12.4

[conda_env.txt](https://github.com/slaclab/pydm/files/10421345/conda_env.txt)

**Comment by jbellister-slac** [comment]
Thanks for reporting! This looks to be a manifestation of the issue with python 3.10 in #951. We should be able to take a look at that soon and get this (and other instances) fixed as part of that. In the mean time if you are able to use an environment with python 3.9 (or lower) it should work.
