### ISSUE TITLE
Make PyDMDrawingPolyline easier to use

### ISSUE THREAD

**Issue by Ryan-McClanahan** [slaclab/pydm#964]
**What's the problem this feature will solve?**

* PyDMDrawingPolyline(s) are drawn by adding or removing points to the points field of the widget.  It would make the widget much more usable if points could be added or removed using the basic settings editor.  Currently the existing points can be edited, but cannot be added or removed from.  Making the points rearrangeable would also greatly improve the usability of the widget.  

* Also, adding an update button to the basic settings editor would increase usability, as currently the save button closes the window, and must be pressed to visually update the widget.  So, when making a bunch of changes using this window the window would have to be launched and closed several times.

![image](https://user-images.githubusercontent.com/93741302/215834087-2e253c5d-477a-44bf-9dde-098cbe540d47.png)

**Comment by nstelter-slac** [comment]
Hi,

Added update button and ability to swap points with drag and drop here: https://github.com/slaclab/pydm/pull/1022

As for adding and removing points, looks like this can currently be done in the points window of the settings-editor, with "Right-click->Add row" and "Right-click->Delete row (when hovering over an existing row)"

**Comment by Ryan-McClanahan** [comment]
Cool!  Can't wait to try it out!
