### ISSUE TITLE
Designer and PyDMShellCommand

### ISSUE THREAD

**Issue by epaiser** [slaclab/pydm#968]
**Describe the bug**

Hi I'm experiencing a problem with the Designer and PyDMShellCommand. I'm still trying to figure out if it's a PyDM issue or something related to Designer.
When choose PyDMShellCommand to a widget and assign a shell script, then running pydm and clicking in the PyDMShellCommand widget, it gave me the error:
- Error in shell command: unexpected EOF while parsing (<unknown>, line 0)

**Expected behavior**

I expected the script should be called.

**Steps to Reproduce**

Just create a empty widget with Designer and add a PyDMShellCommand set to call a gnome-terminal (for example).

**Possible Solution**
 
If I get the ui file and remove some properties like:
     property name="environmentVariables" stdset="0"
      string/
     /property

Then it works.

see attached ui file with the extension .txt

**My Platform**

**Additional context**

[pydm_shellcmd.ui.txt](https://github.com/slaclab/pydm/files/10680550/pydm_shellcmd.ui.txt)

**Comment by epaiser** [comment]
I don't know what is the origin of the problem, but clicking on the default button in
Object Inspector->PyDMShellCommand->environmentVariables 
in the Designer it works properly.

**Comment by jbellister-slac** [comment]
Thanks for reporting! Looks like an issue with the shell command not working when the environment variable property gets saved as an empty string. Fix should be very simple, will get that done soon. In the mean time I think your work around is the easiest way to fix it.
