### ISSUE TITLE
BUG: PyDMToolTip and disconnected channels

### ISSUE THREAD

**Issue by YektaY** [slaclab/pydm#978]
**Describe the bug**
When a PyDMToolTip is set, it will not be amended when a channel is disconnected. 

**Expected behavior**
appends the disconnected message to end of tool tip.
 
**Steps to Reproduce**
set the PyDMToolTip with any value. check tool tip on a widget with a disconnected channel.

**Comment by nstelter-slac** [comment]
hi,

the behavior i'm seeing atm is the tooltip keeps displaying the last value of the channel before it was disconnected.

do we want to remove the channel's last value from the tooltip string and replace it with some text like "Channel is disconnected"?

**Comment by YektaY** [comment]
Yes, It would be better to remove the value as to not confuse the user, who may still think the value they see is valid
