### ISSUE TITLE
Request: support for drop-down menus

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#99]
It could be implemented as part of PyDMRelatedDisplayButton or a new widget altogether.

As in EDM:
![image](https://user-images.githubusercontent.com/5139267/29733530-6b83b3d4-89a2-11e7-8ada-97b31c3431d1.png)

Macros should be inherited from the parent display, and per-entry you should be able to specify macros that may override the parent ones.

**Comment by hhslepicka** [comment]
Closed via #465
