### ISSUE TITLE
Race Condition PyDMLineEdit vs Default Focus Widget

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pydm#993]
**Describe the bug**

On loading a screen, if a `PyDMLineEdit` widget is given focus before the PV connects (hypothesis), then the widget never loads the initial text from the PV.

I think this is because qt gives a widget focus automatically if it is tab-able and first in the tab order, tab focus is enabled by default, and we skip updating the line edit text if the widget has focus: https://github.com/slaclab/pydm/blob/b16e89ebea218604437bb767c3d77f379958854b/pydm/widgets/line_edit.py#L236-L237

**Expected behavior**

All widgets should initialize with their channel value.

**Steps to Reproduce**

Create a screen with a lot of line edits, maybe

**Possible Solution**
 
- On first load, ignore the focus state of the widget?
- On first load/new value, cache the value even if we don't update the display, so that we can update it on the focus out event?
- Disable tab focus in `PyDMLineEdit`?

**My Platform**

Running on RHEL7, xforwarded to win10 and to osx (same behavior)
Python 3.9
Pydm 1.19.0
qt 5.12.9
pyqt 5.12.3

**Comment by ZLLentz** [comment]
I should have added: we noticed this because, on load, we noticed that one of our line edits was always opening blank with the cursor in the box as if we'd already selected the widget

**Comment by jbellister-slac** [comment]
Thanks for reporting! I think your analysis is correct, I can reproduce that behavior by forcing a delay in receiving a value from the data plugin by inserting a sleep between channel connection and callback setup. Disabling tab focus altogether in the line edit does fix it. I'll poke around further and see what the best way of doing the first suggestion might look like
